const                     
  MainLngBase       = 1000;
  LngEvtBase        = 500;
  LngBaseEnglish    = MainLngBase+0;
  LngBaseEnglishEvt = LngBaseEnglish+LngEvtBase;

  LngBaseRussian    = MainLngBase+1000;
  LngBaseRussianEvt = LngBaseRussian+LngEvtBase;

  LngBaseGerman     = MainLngBase+2000;
  LngBaseGermanEvt  = LngBaseGerman+LngEvtBase;

  LngBaseDanish     = MainLngBase+3000;
  LngBaseDanishEvt  = LngBaseDanish+LngEvtBase;
  


 eiStart            = 0;

 eiModemCmdInit     = 1;
 eiModemCmdAnswer   = 2;
 eiModemCmdPrefix   = 3;
 eiModemCmdSuffix   = 4;
 eiModemCmdHangup   = 5;
 eiModemCmdExit     = 6;

 eiRplStation       = 7;
 eiRplModem         = 8;
 eiRplRestriction   = 9;

 eiRestrictRqd      = 10;
 eiRestrictFrb      = 11;

 eiAccFilesRqd      = 12;
 eiAccFilesFrb      = 13;

 eiAccNodesRqd      = 14;
 eiAccNodesFrb      = 15;

 eiAccLinkRqd       = 16;
 eiAccLinkFrb       = 17;

 eiAccSpeedMin      = 18;

 eiAccNoFreqs       = 19;
 eiNumRings         = 20;

 eiModemDisaReinit  = 21;

 eiAccProtected     = 22;

 eiFreqPwdDur       = 23; 
 eiFreqPwdSz        = 24; 
 eiFreqPwdCnt       = 25; 

 eiFreqPubDur       = 26; 
 eiFreqPubSz        = 27; 
 eiFreqPubCnt       = 28; 

 eiTrsFilesRqd	    = 29;
 eiTrsFilesFrb	    = 30;

 eiAccNoNiagara     = 31;
 eiTrsNoNiagara	    = 32;

 eiAccNoHydra       = 33;
 eiTrsNoHydra       = 34;

 eiAccNoZmodem      = 35;
 eiTrsNoZmodem      = 36;

 eiAccNoFTS1        = 37;

 eiAccNoIncoming    = 38;

 eiAccNoYooHoo      = 39;
 eiTrsNoYooHoo      = 40;

 eiAccNoEMSI        = 41;
 eiTrsNoEMSI        = 42;

 eiDoor             = 43;
 eiPassword         = 44;

 eiAccNoDummyZ	    = 45;
 eiTrsNoDummyZ	    = 46;

 eiTrsSpeedMin	    = 47;

 eiLogEMSI	    = 48;

 eiAccCPSMin	    = 49;
 eiTrsCPSMin	    = 50;

 eiAccDurMax   	    = 51;
 eiTrsDurMax        = 52;

 eiAccBPSEfMin      = 53;
 eiTrsBPSEfMin      = 54;

 eiResponseFormat   = 55;
 eiInputFormat      = 56;

 eiInputWdReset     = 57;
 eiInputWdExtApp    = 58;

 eiModemErrExtApp   = 59;
 
 eiAccListed	    = 60;

 eiLoginScript      = 61;

 eiAccNoCram        = 62;
 eiTrsNoCram        = 63;

 eiStop             = 64;
